name: Perl

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '42 5 * * *'

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        runner: [ubuntu-latest] #, macos-latest, windows-latest]
        perl: ['5.36' ]
        module:
          - 'Dist::Zilla::Plugin::AutoPrereqs'
          - 'Dist::Zilla::Plugin::Git::Check'
          - 'Dist::Zilla::Plugin::Git::Commit'
          - 'Dist::Zilla::Plugin::Git::Push'
          - 'Dist::Zilla::Plugin::Git::Tag'
          - 'Dist::Zilla::Plugin::GitHub::Meta'
          - 'Dist::Zilla::Plugin::InstallGuide'
          - 'Dist::Zilla::Plugin::MetaJSON'
          - 'Dist::Zilla::Plugin::ModuleBuild'
          - 'Dist::Zilla::Plugin::NextRelease'
          - 'Dist::Zilla::Plugin::NextVersion::Semantic'
          - 'Dist::Zilla::Plugin::PerlTidy'
          - 'Dist::Zilla::Plugin::PkgVersion'
          - 'Dist::Zilla::Plugin::PodSyntaxTests'
          - 'Dist::Zilla::Plugin::PodWeaver'
          - 'Dist::Zilla::Plugin::Prereqs'
          - 'Dist::Zilla::Plugin::PreviousVersion::Changelog'
          - 'Dist::Zilla::Plugin::Test::CPAN::Changes'
          - 'Dist::Zilla::Plugin::Test::Perl::Critic'
          - 'Dist::Zilla::Plugin::Test::UnusedVars'
          - 'Dist::Zilla::PluginBundle::Basic'
          - 'Dist::Zilla::PluginBundle::Filter'

          - 'Class::Singleton'
          - 'Date::Calc'
          - 'DateTime'
          - 'DateTime::Format::ISO8601'
          - 'DateTime::Locale'
          - 'DB_File'
          - 'Exception::Class'
          - 'File::Compare'
          - 'File::Slurp'
          - 'HTTP::Request'
          - 'IO::Capture::Stderr'
          - 'LWP::UserAgent'
          - 'Module::Build'
          - 'Readonly'
          - 'Scalar::Util'
          - 'String::Interpolate::Named'
          - 'Test::Exception'
          - 'Test::More'
          - 'Try::Tiny'
          - 'YAML::XS'
        exclude:
          - runner: windows-latest
            perl: '5.36'

    runs-on: ${{matrix.runner}}
    name: OS ${{matrix.runner}} Perl ${{matrix.perl}}

    steps:
    - uses: actions/checkout@v2

    - name: Set up perl
      uses: shogo82148/actions-setup-perl@v1
      with:
          perl-version: ${{ matrix.perl }}
          distribution: ${{ ( startsWith( matrix.runner, 'windows-' ) && 'strawberry' ) || 'default' }}

    - name: Show Perl Version
      run: |
        perl -v

    - name: Install Modules
      run: |
        cpanm -v
        cpanm @{{ matrix.module }}

    - name: Show Errors on Windows
      if:  ${{ failure() && startsWith( matrix.runner, 'windows-')}}
      run: |
         ls -l C:/Users/
         ls -l C:/Users/RUNNER~1/
         cat C:/Users/runneradmin/.cpanm/work/*/build.log

    - name: Show Errors on Ubuntu
      if:  ${{ failure() && startsWith( matrix.runner, 'ubuntu-')}}
      run: |
         cat /home/runner/.cpanm/work/*/build.log

    - name: Show Errors on OSX
      if:  ${{ failure() && startsWith( matrix.runner, 'macos-')}}
      run: |
         cat  /Users/runner/.cpanm/work/*/build.log
